#!/bin/sh

# Symlink bin directory
bin_dir=$HOME/bin
sym_dirs=$(find "$PWD/bin" -maxdepth 1 -mindepth 1)

mkdir -p $bin_dir

for f in $sym_dirs; do
  name=$(basename $f)

  if [ -d $f ] ; then
	ln -s $f/bin/$name $bin_dir/$name
  else
	ln -s $f $bin_dir/$name
  fi
done

# Symlink everything else
home_dir=$HOME
sym_dirs=$(find "$PWD/bash" "$PWD/git" "$PWD/rubygems" "$PWD/vim" -maxdepth 1 -mindepth 1)

for f in $sym_dirs; do
  name=$(basename $f)
  ln -s $f $home_dir/.$name
done
