set noesckeys
set nocompatible
execute pathogen#infect()

syntax enable
filetype plugin indent on

" Load fzf
set rtp+=/usr/local/Cellar/fzf/0.9.4-1

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

" Settings
"
let mapleader=','
let base16colorspace=256

colorscheme base16-default

set nobackup
set noswapfile
set nowritebackup

set ttimeout
set ttimeoutlen=50
set grepprg=ag\ --nogroup\ --nocolor
set backspace=indent,eol,start
set smarttab
set expandtab
set shiftwidth=2
set softtabstop=2
set shiftround
set autoindent
set complete-=i
set nrformats-=octal
set hidden
set splitbelow
set number
set ruler
set hlsearch
set incsearch
set wildmenu
set laststatus=2
set autoread
set lazyredraw
set nocursorline
set scrolljump=8
set background=dark

" Plugin settings
"
let g:netrw_localrmdir='rm -fR'
let g:netrw_list_hide='.git,.svn,.idea'
let g:NERDTreeHighlightCursorline=0

" Commands
"
command! W :execute ':silent w !sudo tee % > /dev/null' | :edit!
command! QflistClear :call setqflist([])

" Mappings
"
nnoremap <Leader>ve :edit $MYVIMRC<CR>
nnoremap <Leader>vs :source $MYVIMRC<CR>
nnoremap <Leader>p :put+<CR>
noremap <Leader>y :yank+<CR>
nnoremap <Leader>nf :NERDTreeFind<CR>
nnoremap <Leader>nt :NERDTreeToggle<CR>
nnoremap <Leader>o :!open %<CR>
nnoremap <silent> <Leader>cp :let @+=expand("%:p")<CR>
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
nnoremap <silent> <C-p> :call fzf#run({'sink': 'edit'})<CR>
