# Terminal device interface options
#
stty -ixon

# Shell options
#
shopt -s autocd
shopt -s cdspell
shopt -s dirspell
shopt -s globstar

# Exports
#
export PS1="\W\[\033[0;32m\]\$(__git_ps1 ' (%s)')\[\033[0m\] \$ "
export PATH="$PATH:$HOME/bin"
export EDITOR='vim'
export CLICOLOR=1

# Language version management
#
eval "$(rbenv init -)"
eval "$(pyenv init -)"

# Sources
#
. $(brew --prefix)/etc/bash_completion
. $(brew --prefix)/Cellar/m/0.1.1/share/m/m
